apiVersion: batch/v1beta2
kind: CronJob
metadata:
  name: cron
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date
            env:
            - name: MY_ENV
              value: prod
            image: centos
            name: cron
            volumeMounts: []
          restartPolicy: OnFailure
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
